/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as GuestIndexRouteImport } from './routes/_guest/index'
import { Route as GuestPharmacyRouteImport } from './routes/_guest/pharmacy'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as GuestGalleryRouteImport } from './routes/_guest/gallery'
import { Route as GuestDoctorsRouteImport } from './routes/_guest/doctors'
import { Route as GuestDepartmentsRouteImport } from './routes/_guest/departments'
import { Route as GuestContactRouteImport } from './routes/_guest/contact'
import { Route as GuestCareerRouteImport } from './routes/_guest/career'
import { Route as GuestAboutRouteImport } from './routes/_guest/about'
import { Route as ProtectedAdminIndexRouteImport } from './routes/_protected/admin/index'
import { Route as ProtectedAdminContactsRouteImport } from './routes/_protected/admin/contacts'
import { Route as GuestServicesServiceRouteImport } from './routes/_guest/services/$service'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestIndexRoute = GuestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuestRoute,
} as any)
const GuestPharmacyRoute = GuestPharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => GuestRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const GuestGalleryRoute = GuestGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => GuestRoute,
} as any)
const GuestDoctorsRoute = GuestDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => GuestRoute,
} as any)
const GuestDepartmentsRoute = GuestDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => GuestRoute,
} as any)
const GuestContactRoute = GuestContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => GuestRoute,
} as any)
const GuestCareerRoute = GuestCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => GuestRoute,
} as any)
const GuestAboutRoute = GuestAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => GuestRoute,
} as any)
const ProtectedAdminIndexRoute = ProtectedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminContactsRoute = ProtectedAdminContactsRouteImport.update({
  id: '/admin/contacts',
  path: '/admin/contacts',
  getParentRoute: () => ProtectedRoute,
} as any)
const GuestServicesServiceRoute = GuestServicesServiceRouteImport.update({
  id: '/services/$service',
  path: '/services/$service',
  getParentRoute: () => GuestRoute,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof GuestAboutRoute
  '/career': typeof GuestCareerRoute
  '/contact': typeof GuestContactRoute
  '/departments': typeof GuestDepartmentsRoute
  '/doctors': typeof GuestDoctorsRoute
  '/gallery': typeof GuestGalleryRoute
  '/login': typeof GuestLoginRoute
  '/pharmacy': typeof GuestPharmacyRoute
  '/': typeof GuestIndexRoute
  '/services/$service': typeof GuestServicesServiceRoute
  '/admin/contacts': typeof ProtectedAdminContactsRoute
  '/admin': typeof ProtectedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof GuestAboutRoute
  '/career': typeof GuestCareerRoute
  '/contact': typeof GuestContactRoute
  '/departments': typeof GuestDepartmentsRoute
  '/doctors': typeof GuestDoctorsRoute
  '/gallery': typeof GuestGalleryRoute
  '/login': typeof GuestLoginRoute
  '/pharmacy': typeof GuestPharmacyRoute
  '/': typeof GuestIndexRoute
  '/services/$service': typeof GuestServicesServiceRoute
  '/admin/contacts': typeof ProtectedAdminContactsRoute
  '/admin': typeof ProtectedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_guest': typeof GuestRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_guest/about': typeof GuestAboutRoute
  '/_guest/career': typeof GuestCareerRoute
  '/_guest/contact': typeof GuestContactRoute
  '/_guest/departments': typeof GuestDepartmentsRoute
  '/_guest/doctors': typeof GuestDoctorsRoute
  '/_guest/gallery': typeof GuestGalleryRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/pharmacy': typeof GuestPharmacyRoute
  '/_guest/': typeof GuestIndexRoute
  '/_guest/services/$service': typeof GuestServicesServiceRoute
  '/_protected/admin/contacts': typeof ProtectedAdminContactsRoute
  '/_protected/admin/': typeof ProtectedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/career'
    | '/contact'
    | '/departments'
    | '/doctors'
    | '/gallery'
    | '/login'
    | '/pharmacy'
    | '/'
    | '/services/$service'
    | '/admin/contacts'
    | '/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/career'
    | '/contact'
    | '/departments'
    | '/doctors'
    | '/gallery'
    | '/login'
    | '/pharmacy'
    | '/'
    | '/services/$service'
    | '/admin/contacts'
    | '/admin'
  id:
    | '__root__'
    | '/_guest'
    | '/_protected'
    | '/_guest/about'
    | '/_guest/career'
    | '/_guest/contact'
    | '/_guest/departments'
    | '/_guest/doctors'
    | '/_guest/gallery'
    | '/_guest/login'
    | '/_guest/pharmacy'
    | '/_guest/'
    | '/_guest/services/$service'
    | '/_protected/admin/contacts'
    | '/_protected/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GuestRoute: typeof GuestRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/': {
      id: '/_guest/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof GuestIndexRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/pharmacy': {
      id: '/_guest/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof GuestPharmacyRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/gallery': {
      id: '/_guest/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GuestGalleryRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/doctors': {
      id: '/_guest/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof GuestDoctorsRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/departments': {
      id: '/_guest/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof GuestDepartmentsRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/contact': {
      id: '/_guest/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof GuestContactRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/career': {
      id: '/_guest/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof GuestCareerRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/about': {
      id: '/_guest/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof GuestAboutRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_protected/admin/': {
      id: '/_protected/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/contacts': {
      id: '/_protected/admin/contacts'
      path: '/admin/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof ProtectedAdminContactsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_guest/services/$service': {
      id: '/_guest/services/$service'
      path: '/services/$service'
      fullPath: '/services/$service'
      preLoaderRoute: typeof GuestServicesServiceRouteImport
      parentRoute: typeof GuestRoute
    }
  }
}

interface GuestRouteChildren {
  GuestAboutRoute: typeof GuestAboutRoute
  GuestCareerRoute: typeof GuestCareerRoute
  GuestContactRoute: typeof GuestContactRoute
  GuestDepartmentsRoute: typeof GuestDepartmentsRoute
  GuestDoctorsRoute: typeof GuestDoctorsRoute
  GuestGalleryRoute: typeof GuestGalleryRoute
  GuestLoginRoute: typeof GuestLoginRoute
  GuestPharmacyRoute: typeof GuestPharmacyRoute
  GuestIndexRoute: typeof GuestIndexRoute
  GuestServicesServiceRoute: typeof GuestServicesServiceRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestAboutRoute: GuestAboutRoute,
  GuestCareerRoute: GuestCareerRoute,
  GuestContactRoute: GuestContactRoute,
  GuestDepartmentsRoute: GuestDepartmentsRoute,
  GuestDoctorsRoute: GuestDoctorsRoute,
  GuestGalleryRoute: GuestGalleryRoute,
  GuestLoginRoute: GuestLoginRoute,
  GuestPharmacyRoute: GuestPharmacyRoute,
  GuestIndexRoute: GuestIndexRoute,
  GuestServicesServiceRoute: GuestServicesServiceRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAdminContactsRoute: typeof ProtectedAdminContactsRoute
  ProtectedAdminIndexRoute: typeof ProtectedAdminIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminContactsRoute: ProtectedAdminContactsRoute,
  ProtectedAdminIndexRoute: ProtectedAdminIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  GuestRoute: GuestRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
